"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const inventory_controller_1 = require("../controllers/inventory.controller");
const inventory_ledger_controller_1 = require("../controllers/inventory-ledger.controller");
const auth_middleware_1 = require("../middleware/auth.middleware");
const branchAuth_middleware_1 = require("../middleware/branchAuth.middleware");
const organizationAccess_middleware_1 = require("../middleware/organizationAccess.middleware");
const router = (0, express_1.Router)();
const orgAccess = (0, organizationAccess_middleware_1.requireOrganizationAccess)();
router.get("/tax-codes", inventory_controller_1.getTaxCodes);
router.get("/products/:organizationId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, inventory_controller_1.getProducts);
router.get("/products/:organizationId/expiring", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, inventory_controller_1.getExpiringProducts);
router.get("/products/:organizationId/expired", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, inventory_controller_1.getExpiredProducts);
router.get("/products/:organizationId/low-stock", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, inventory_controller_1.getLowStockProducts);
router.get("/:id", auth_middleware_1.authenticate, inventory_controller_1.getProductById);
router.post("/:organizationId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), inventory_controller_1.createProduct);
router.post("/:organizationId/products", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), inventory_controller_1.createProducts);
router.put("/:organizationId/product/:id", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), inventory_controller_1.updateProduct);
router.delete("/:organizationId/product/:id", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), inventory_controller_1.deleteProduct);
router.post("/:organizationId/product/:id/adjust", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), inventory_controller_1.adjustStock);
router.post("/:organizationId/product/:id/damage", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), inventory_controller_1.markAsDamage);
router.post("/:organizationId/product/:id/process-expired", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), inventory_controller_1.processExpiredStock);
// Inventory Ledger Routes - Append-only ledger for complete inventory history
router.post("/:organizationId/ledger/in", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), inventory_ledger_controller_1.addStockToInventory);
router.post("/:organizationId/ledger/out", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), inventory_ledger_controller_1.removeStockFromInventory);
router.post("/:organizationId/ledger/adjustment", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), inventory_ledger_controller_1.adjustInventoryStock);
router.get("/:organizationId/ledger", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, inventory_ledger_controller_1.getInventoryLedger);
router.get("/:organizationId/ledger/summary", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, inventory_ledger_controller_1.getInventorySummaryReport);
router.get("/:organizationId/ledger/current-stock/:productId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, inventory_ledger_controller_1.getCurrentStockLevel);
router.get("/:organizationId/ledger/history/:productId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, inventory_ledger_controller_1.getProductInventoryHistory);
router.post("/:organizationId/ledger/recalculate/:productId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "BRANCH_MANAGER"), inventory_ledger_controller_1.recalculateStock);
exports.default = router;
