"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const organization_controller_1 = require("../controllers/organization.controller");
const auth_middleware_1 = require("../middleware/auth.middleware");
const upload_middleware_1 = require("../middleware/upload.middleware");
const organizationAccess_middleware_1 = require("../middleware/organizationAccess.middleware");
const router = (0, express_1.Router)();
const orgAccess = (0, organizationAccess_middleware_1.requireOrganizationAccess)();
const orgAccessById = (0, organizationAccess_middleware_1.requireOrganizationAccess)("id");
router.get("/", auth_middleware_1.authenticate, organization_controller_1.getUserOrganizations);
router.get("/:id", auth_middleware_1.authenticate, orgAccessById, organization_controller_1.getOrganizationById);
router.post("/", auth_middleware_1.authenticate, organization_controller_1.createOrganization);
router.put("/:id", auth_middleware_1.authenticate, orgAccessById, organization_controller_1.updateOrganization);
router.put("/avatar/:id", auth_middleware_1.authenticate, orgAccessById, upload_middleware_1.uploadSingle.single("avatar"), organization_controller_1.updateOrganizationAvatar);
router.delete("/:id", auth_middleware_1.authenticate, orgAccessById, organization_controller_1.deleteOrganization);
router.get("/:id/settings", auth_middleware_1.authenticate, orgAccessById, organization_controller_1.getOrgSettings);
router.patch("/:id/settings", auth_middleware_1.authenticate, orgAccessById, organization_controller_1.updateOrgSettings);
router.post("/:organizationId/invite", auth_middleware_1.authenticate, orgAccess, organization_controller_1.inviteUser);
router.post("/:organizationId/bulk-invite", auth_middleware_1.authenticate, orgAccess, organization_controller_1.bulkInviteUsers);
router.post("/accept-invitation/:token", organization_controller_1.acceptInvitation);
router.get("/get-invitation/:token", organization_controller_1.getInvitationDetails);
router.put("/cancel-invitation/:id", organization_controller_1.cancelInvitation);
router.put("/decline-invitation/:token", organization_controller_1.declineInvitation);
router.get("/:organizationId/users", auth_middleware_1.authenticate, orgAccess, organization_controller_1.getOrganizationUsers);
router.delete("/:organizationId/users/:userId", auth_middleware_1.authenticate, orgAccess, organization_controller_1.removeUserFromOrganization);
exports.default = router;
