"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const report_controller_1 = require("../controllers/report.controller");
const auth_middleware_1 = require("../middleware/auth.middleware");
const branchAuth_middleware_1 = require("../middleware/branchAuth.middleware");
const organizationAccess_middleware_1 = require("../middleware/organizationAccess.middleware");
const router = (0, express_1.Router)();
const orgAccess = (0, organizationAccess_middleware_1.requireOrganizationAccess)();
router.get("/sales/:organizationId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), report_controller_1.getSalesReport);
router.get("/inventory/:organizationId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), report_controller_1.getInventoryReport);
router.get("/debtors/:organizationId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), report_controller_1.getDebtorsReport);
router.get("/debt-payments/:organizationId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "BRANCH_MANAGER"), report_controller_1.getDebtPaymentsReport);
router.get("/cash-flow/:organizationId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "BRANCH_MANAGER"), report_controller_1.getCashFlowReport);
router.get("/stock/:organizationId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), report_controller_1.getStockReport);
router.get("/stock-history/:organizationId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), report_controller_1.getStockHistory);
router.get("/profit/:organizationId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "BRANCH_MANAGER"), report_controller_1.getProfitReportController);
router.get("/export/:reportType/:organizationId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "SELLER", "BRANCH_MANAGER"), report_controller_1.exportReport);
// C9: X/Z daily fiscal reports (RRA CIS/VSDC spec §6)
router.get("/daily/:organizationId", auth_middleware_1.authenticate, orgAccess, branchAuth_middleware_1.branchAuth, (0, auth_middleware_1.authorize)("ADMIN", "ACCOUNTANT", "BRANCH_MANAGER"), report_controller_1.getDailyReport);
exports.default = router;
