import { apiClient } from "./api-client"

export type InvoicePdfFormat = "A4" | "A5" | "80mm"

/** Fetch the authoritative PDF bytes generated by the backend. */
export async function getInvoicePdfBlob(saleId: string | number, format: InvoicePdfFormat = "A4"): Promise<Blob> {
  const response = await apiClient.getInvoicePdf(saleId, format)
  const blob = await response.blob()
  if (blob.type !== "application/pdf" || blob.size < 1_000) {
    throw new Error("The server returned an invalid invoice PDF")
  }
  return blob
}

/**
 * CIS/VSDC spec §7.18/§15: "print only one original receipt. Reprint shall
 * have a watermark with mention Copy." There is no separate "download copy"
 * action — every deliberate download registers itself first; the first one
 * for a given sale renders as the original, every one after automatically
 * comes back watermarked COPY from the backend.
 */
export async function downloadInvoicePdf(
  saleId: string | number,
  filename: string,
  format: InvoicePdfFormat = "A4",
): Promise<boolean> {
  await apiClient.reprintSale(saleId)
  const blob = await getInvoicePdfBlob(saleId, format)
  const url = URL.createObjectURL(blob)
  const link = document.createElement("a")
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  link.remove()
  setTimeout(() => URL.revokeObjectURL(url), 2_000)
  return true
}

/** Same "first is original, rest are COPY" registration as {@link downloadInvoicePdf} — sharing hands out a receipt file too. */
export async function shareInvoicePdf(
  saleId: string | number,
  filename: string,
  format: InvoicePdfFormat = "A4",
): Promise<boolean> {
  await apiClient.reprintSale(saleId)
  const blob = await getInvoicePdfBlob(saleId, format)
  const file = new File([blob], filename, { type: "application/pdf" })
  const shareData: ShareData = { title: filename.replace(/\.pdf$/i, ""), files: [file] }

  if (typeof navigator.share === "function" && (!navigator.canShare || navigator.canShare(shareData))) {
    await navigator.share(shareData)
    return true
  }

  const url = URL.createObjectURL(blob)
  const link = document.createElement("a")
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  link.remove()
  setTimeout(() => URL.revokeObjectURL(url), 2_000)
  return false
}
